### ISSUE TITLE
use arrayjoin and sequential

### ISSUE THREAD

**Issue by jcupitt** [monostream/tifig#1]
Hello, I liked your converter. I noticed a couple of small things looking though the code:

- You could use `arrayjoin` to improve the joining process. It can join any number of images into a rectangular grid in a single operation:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-arrayjoin

   it should reduce memory use, and help the converter scale to larger images. 

- You could set the sequential access hint -- this would let libvips overlap decode and encode. Change `new_from_file` to be:

```c++
        VImage im = VImage::new_from_file(argv[1], VImage::option()->set("access", "sequential"));
```

  it should produce a small speedup.

**Comment by monostefan** [comment]
Hi @jcupitt, thank you very very much for the tip! I implemented your suggestion in 59a7bd549ae58426a52d1d303ffc8d5a4c2082d9 and it's indeed a lot faster. On my machine its saves around 160ms to build a full image. Awesome!

Switching to sequential access is also a great idea, however, by now we decode HEVC tiles directly to memory using libav. So gone are the tempfiles and unnecessary IO slow downs. ;)

Also many kudos for libvips in general! It's a very pleasant API to use and faster than lightning. Keep up the good work, it's appreciated!

**Comment by jcupitt** [comment]
That's great! I'm glad it helped.

Do you mean you are using `new_from_memory` now? If so, you're right, seq is not relevant. If you are still going via JPEG, then seq should give a speedup.

**Comment by monostefan** [comment]
Yup, we're using `new_from_memory` since that's another great way to speed up things :wink: . Thanks again!

**Comment by jcupitt** [comment]
Off-topic: there's talk of adding HEIF to libvips as a supported format. Would you be interested in getting your loader into core libvips? It shouldn't be a large amount of work.

**Comment by monostefan** [comment]
We like that idea ;). At the moment, we try to get tifig working for the cause we need it for: Creating thumbnails of HEIC images in a cloud solution. Once we get there, we sure would love to integrate our solution into vips. However, there's two things that probably need to be considered: Nokiatech's heif library is C++ only at the moment therefore doesn't really fit into vips ecosystem. The other point is HEVC decoding. We're relying on libav, which could be integrated, but is a huge monster itself.

**Comment by jcupitt** [comment]
libvips has a C API, but uses C++ internally, so I think that would be OK.

libav is indeed a huge monster :( A `heifload` operator would need to be optional, since it would probably be unacceptable for many users.
