### ISSUE TITLE
to rotate or not to rotate

### ISSUE THREAD

**Issue by Eriken** [monostream/tifig#10]
Looking at your commit log I see you try to rotate the images based on its metadata:
https://github.com/monostream/tifig/commit/5697f12410805e60e09ad3742a8ab27059a51424

However, after testing the output from your binary this does not seem to be the case. The orientation tag is passed to the metadata of the output image, and the image is not rotated. This looks like the desired behaviour if you do not intend to rotate the image. 

Is this intentional?

**Comment by monostefan** [comment]
We only try to rotate images when exporting to something else than jpeg. When converting to jpeg, the exif rotation should be kept the same way as it is used in the heic image. Do you have any sample image where the output image is rotated incorrectly?

**Comment by Eriken** [comment]
Aha. That makes sense then. No, everything looks good as of now, I just use IM for rotation.
You should consider embedding the heif exif into the jpegs. As of now I use a very simple tool to just extract the exif blob, but it would be nice to just have one tool.

The tool is made by me, but I am not a c++ developer so its not very pretty:
https://gist.github.com/Eriken/8cc34e27c4581a4340492ff8f7c85c05

**Comment by monostefan** [comment]
Keeping Exif metadata in the converted images is something we have on the radar, I made some first steps in 91ed2bf4e4c3284a5052ceb5bfc6f0f5df79df41 and added the task to our todo list. However, vips seems to not really support setting Exif metadata on newly created image from a binary blob at the moment. Extracting the data to a seperate file first and mergin it into jpeg afterwards is sort of hack for me, I would prefer a cleaner solution where we can do this in one step directly. Keep watching branch `preserve_exif` for progress, however, I will not give any ETA for this 😋 .

I take the liberty to close this issue, feel free to reopen it when you see any case where we rotate images incorrectly

**Comment by monostefan** [comment]
Btw, check out the current master branch, Exif support has arrived ;)

**Comment by Eriken** [comment]
Awesome, thank you!
