### ISSUE TITLE
No package 'vips-cpp' found

### ISSUE THREAD

**Issue by muggle2012** [monostream/tifig#13]
I work on Mac OSX High Sierra. After install vips and ffmpeg via
$ brew install vips ffmpeg
I tried to build tifig. However, the following error happened during cmake
$ cmake ..
-- Checking for module 'vips-cpp'
--   No package 'vips-cpp' found
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindPkgConfig.cmake:424 (message):
  A required package was not found

Hope some one can help. Thanks.

**Comment by monostefan** [comment]
Hmm, that's weird. Can you paste the output of `brew info vips` and `pkg-config vips-cpp --libs` ,  then I can might have some more clue what's wrong on your machine.

**Comment by muggle2012** [comment]
Thanks for the suggestion. everything is fine with brew info vips. When I run pkg-config vips-cpp --libs, it suggests me to add the folder containing vips-cpp.pc to PKG_CONFIG_PATH. There are other cmake errors such as
-- Checking for module 'vips-cpp'
--   Package 'libexif', required by 'vips', not found

$ pkg-config libexif --libs
Package libexif was not found in the pkg-config search path.
Perhaps you should add the directory containing `libexif.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libexif' found

I am not sure whether the directory should be added by vips or tifig. For me, these packages are installed in /usr/local/Cellar/

Thanks, I will continue to add these directories to PKG_CONFIG_PATH.

**Comment by monostefan** [comment]
Ok, seems like your `PKG_CONFIG_PATH` was messed up somehow. :crossed_fingers: it builds now.

**Comment by monostefan** [comment]
Did building tifig finally work for you?

**Comment by muggle2012** [comment]
Yes, it works. Thanks. The issue can be closed.
