### ISSUE TITLE
could not make

### ISSUE THREAD

**Issue by ybagdasa** [monostream/tifig#16]
Hi,
I'm running on:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

I followed the read me file instructions but could not make the binary:

Scanning dependencies of target tifig
[ 92%] Building CXX object CMakeFiles/tifig.dir/src/main.cpp.o
In file included from /home/yelena/tifig/src/loader.hpp:7:0,
                 from /home/yelena/tifig/src/main.cpp:5:
/home/yelena/tifig/src/hevc_decode.hpp: In function ‘RgbData decodeFrame(DataVector)’:
/home/yelena/tifig/src/hevc_decode.hpp:83:40: error: ‘av_packet_alloc’ was not declared in this scope
     AVPacket* packet = av_packet_alloc();
                                        ^
/home/yelena/tifig/src/hevc_decode.hpp:89:45: error: ‘avcodec_send_packet’ was not declared in this scope
     int sent = avcodec_send_packet(c, packet);
                                             ^
/home/yelena/tifig/src/hevc_decode.hpp:97:49: error: ‘avcodec_receive_frame’ was not declared in this scope
     int success = avcodec_receive_frame(c, frame);
                                                 ^
In file included from /home/yelena/tifig/src/loader.hpp:8:0,
                 from /home/yelena/tifig/src/main.cpp:5:
/home/yelena/tifig/src/imaging.hpp: In function ‘vips::VImage createVipsThumbnail(vips::VImage&, Opts&)’:
/home/yelena/tifig/src/imaging.hpp:45:39: error: ‘class vips::VImage’ has no member named ‘tiffsave_buffer’
     VipsBlob* imgBlob = img.autorot().tiffsave_buffer(VImage::option()->set("strip", true));
                                       ^
/home/yelena/tifig/src/imaging.hpp:52:39: error: ‘VIPS_INTERESTING_CENTRE’ was not declared in this scope
         thumbnailOptions->set("crop", VIPS_INTERESTING_CENTRE);
                                       ^
/home/yelena/tifig/src/imaging.hpp:55:12: error: ‘thumbnail_buffer’ is not a member of ‘vips::VImage’
     return VImage::thumbnail_buffer(imgBlob, options.width, thumbnailOptions);
            ^
CMakeFiles/tifig.dir/build.make:62: recipe for target 'CMakeFiles/tifig.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/tifig.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/tifig.dir/all' failed
make[1]: *** [CMakeFiles/tifig.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by monostefan** [comment]
Well, it seems like the installed versions of the ffmpeg and vips libraries are too old. Have you installed the ppa we recommend in the README?

```
# sudo add-apt-repository -y ppa:dhor/myway
# sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
# suod apt-get update
# sudo apt-get install libvips-dev libavcodec-dev libswscale-dev
```

**Comment by ybagdasa** [comment]
I thought I did, but I did it again just in case and now I get a new error:

Scanning dependencies of target tifig
[ 92%] Building CXX object CMakeFiles/tifig.dir/src/main.cpp.o
[ 94%] Building C object CMakeFiles/tifig.dir/src/vips-exif.c.o
[ 95%] Linking CXX executable tifig
/usr/bin/ld: cannot find -lavcodec-ffmpeg
/usr/bin/ld: cannot find -lavutil-ffmpeg
/usr/bin/ld: cannot find -lswscale-ffmpeg
collect2: error: ld returned 1 exit status
CMakeFiles/tifig.dir/build.make:127: recipe for target 'tifig' failed
make[2]: *** [tifig] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/tifig.dir/all' failed
make[1]: *** [CMakeFiles/tifig.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by monostefan** [comment]
`-lavcodec-ffmpeg` seems a little suspicous. Have you installed another ffmpeg somewhere? Maybe try `sudo ldconfig` and build again. If that doesn't help, what does `pkg-config libavcodec --libs --cflags` print on your machine?

If you just want to try out tifig you may also use one of our [static release builds](https://github.com/monostream/tifig/releases).

**Comment by ybagdasa** [comment]
Ok, I will just use those. Thanks.
