### ISSUE TITLE
tifig for Centos

### ISSUE THREAD

**Issue by peacedyc33** [monostream/tifig#21]
I'm trying to install tifig on Centos 7.
I have installed all dependencies, and the output of running "make" is:
> [  2%] Built target h265parser
[  4%] Built target avcparser
[ 88%] Built target common
[ 91%] Built target heifreader
[ 92%] Building CXX object CMakeFiles/tifig.dir/src/main.cpp.o
In file included from /home/gec/tifig/src/loader.hpp:7:0,
                 from /home/gec/tifig/src/main.cpp:5:
/home/gec/tifig/src/hevc_decode.hpp: In function ‘RgbData decodeFrame(DataVector)’:
/home/gec/tifig/src/hevc_decode.hpp:83:40: error: ‘av_packet_alloc’ was not declared in this scope
     AVPacket* packet = av_packet_alloc();
                                        ^
/home/gec/tifig/src/hevc_decode.hpp:89:45: error: ‘avcodec_send_packet’ was not declared in this scope
     int sent = avcodec_send_packet(c, packet);
                                             ^
/home/gec/tifig/src/hevc_decode.hpp:97:49: error: ‘avcodec_receive_frame’ was not declared in this scope
     int success = avcodec_receive_frame(c, frame);
                                                 ^
make[2]: *** [CMakeFiles/tifig.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/tifig.dir/all] Error 2
make: *** [all] Error 2

I don't know what's the issue is. It seems like tifig does not support Centos.

**Comment by Flask** [comment]
hey @peacedyc33 could you shortly paste the version of ffmpeg/libav? My guess is that it is too old and the mentioned functions aren't even there. CentOs tends to be a bit special. E.g. had to alter the PKG_CONFIG_PATH for vips.

Maybe the easiest way would be to get the static binary (attached to each release of tifig).

**Comment by monostefan** [comment]
Do you have any news yet @peacedyc33? As @Flask pointed out, the issue seems to be that your ffmpeg version is too old. tifig requires the quite modern version 3.1, which is probably not available on CentOS 7. I guess the intertubes should help you figure out how to install it, probably building from source is required. And if you don't want to take that burden, the static release verions are actually tested and confirmed to run on CentOS 7 😸.

**Comment by peacedyc33** [comment]
@monostefan Thank you for explaining. Our server is Centos7.3. It might not good timing to achieve this. I'll turn to other things first, and back to check this later.
