### ISSUE TITLE
missing CMakeLists are blocking my build

### ISSUE THREAD

**Issue by themaddoctor** [monostream/tifig#22]
CMake Error at CMakeLists.txt:60 (add_subdirectory):
  The source directory

    /building/graphics/tifig-0.2.1/lib/heif

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:61 (add_subdirectory):
  The source directory

    /building/graphics/tifig-0.2.1/lib/cxxopts

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!

**Comment by themaddoctor** [comment]
Actually, now that I look at it, lib/heif is completely empty.
It's from the source tarball 0.2.1 of december 10

**Comment by Flask** [comment]
@themaddoctor the tarball which github creates on a release does not contain the submodules.. better clone the repository than run `git submodules update --init`

**Comment by themaddoctor** [comment]
Lack of sleep is my problem. Sorted now. Thank you.
