### ISSUE TITLE
macOS Sierra installation

### ISSUE THREAD

**Issue by pelaxa** [monostream/tifig#24]
This is not so much an issue as it is more instructions!  I had to install some additional packages to get things working.

`
> brew install cmake vips ffmpeg libxml2 zlib
> setenv PKG_CONFIG_PATH /usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig
> git clone --recursive https://github.com/monostream/tifig.git
> mkdir tifig/build && cd tifig/build
> cmake ..
> make
`

**Comment by guetux** [comment]
Thanks for the hint! This might be helpful if other people run into this issue. However, I just followed our install instructions on a fresh macOS High Sierra machine and it worked all fine. The only thing we didn't really mention in README is that you might need a decent cmake version installed. Will add that to the README, so thanks again for the insights!
