### ISSUE TITLE
cmake之后，提示错误，是什么原因？

### ISSUE THREAD

**Issue by jassonjackson** [monostream/tifig#25]
<img width="567" alt="2018-02-09 3 11 02" src="https://user-images.githubusercontent.com/35954603/36015945-b18ff47c-0dab-11e8-9f39-dca1cadf84c8.png">

**Comment by monostefan** [comment]
Please try building vips from source as mentioned in the README:

```
sudo apt-get install build-essential pkg-config libglib2.0-dev libexpat1-dev libjpeg-dev libexif-dev libpng-dev libtiff-dev
wget https://github.com/jcupitt/libvips/releases/download/v8.6.1/vips-8.6.1.tar.gz
tar xzf vips-8.6.1.tar.gz
cd vips-8.6.1
./configure
make
sudo make install
```

Hope that works out for you
