### ISSUE TITLE
Release an official docker image

### ISSUE THREAD

**Issue by brendan-rius** [monostream/tifig#29]
I hosted mine here: https://hub.docker.com/r/brendanrius/tifig/ but it would be better if you had your own, and if you set up continuous docker builds.

Doing so can be useful as you can do something like `docker run brendanrius/tifig --version`

**Comment by munzli** [comment]
automated build has been placed at https://hub.docker.com/r/monostream/tifig/

looking at #28 i don't like the idea of having and entrypoint in the Dockerfile but we could add a correct CMD that can be easily overridden.
so as soon as we've done that the next release will also be tagged on docker hub.

**Comment by brendan-rius** [comment]
Cool thanks! Could you also tag docker images based on version numbers of tifig? Thank you!

Also, I fixed #28.

**Comment by mantagen** [comment]
Hmm, https://hub.docker.com/r/monostream/tifig/ seems not to exist any more. Is there a reason for this?

**Comment by Jbarget** [comment]
FYI tried to use https://hub.docker.com/r/monostream/tifig/ but get a 404 so using @brendan-rius's instead for now

**Comment by adrianliechti** [comment]
hi @mantagen
we had actually no idea that this was in use by somebody :)

I updated the Dockerfile to make the image much smaller  for running it (and not testing it), and re-pushed it to docker hub: https://hub.docker.com/r/monostream/tifig/tags. Let us know if this works for you - and feel free to fork and change it.

As we wrote in the readme, tifig is not actively maintained or in use by us anymore...
so do not expect new feature

cheers

**Comment by mantagen** [comment]
Great, thanks @adrianliechti , working well

**Comment by adrianliechti** [comment]
glad to hear :)
