### ISSUE TITLE
Raspberry Pi 

### ISSUE THREAD

**Issue by FastPatioTables** [monostream/tifig#34]
Has anyone had any luck using this on a Raspberry Pi? After a lot of trial and error I got it to build on one of my Pis but can't get it to make on another. I'm looking for advice on what I need to clone from one pi to another so I don't have to rebuild. Any advice?
thanks

**Comment by Flask** [comment]
Hey @FastPatioTables 

By copying from one Pi to another you mean the binary right? That probably wont work, unless you have installed all the necessary libraries on the target Pi.
One way to do it would be to build it static; have a look at https://github.com/monostream/tifig/blob/master/CMakeLists.txt#L16

You than should be able to copy and run the binary without problems.
Let me know if that works for you
