### ISSUE TITLE
tifig can't converting heif files from https://github.com/nokiatech/heif_conformance/tree/master/conformance_files to jpeg files

### ISSUE THREAD

**Issue by snowuyl** [monostream/tifig#36]
Hi monostream,,

    The following are log messages about converting heif files from https://github.com/nokiatech/heif_conformance/tree/master/conformance_files to jpeg files..

https://github.com/nokiatech/heif_conformance/tree/master/conformance_files

build/tifig -i conformance_files/C020.heic -o conformance_files/C020.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C017.heic -o conformance_files/C017.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C033.heic -o conformance_files/C033.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C026.heic -o conformance_files/C026.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C002.heic -o conformance_files/C002.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C004.heic -o conformance_files/C004.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C019.heic -o conformance_files/C019.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C009.heic -o conformance_files/C009.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C031.heic -o conformance_files/C031.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C011.heic -o conformance_files/C011.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C023.heic -o conformance_files/C023.jpg
Exif Data ID (cdsc) not found!
build/tifig -i conformance_files/C032.heic -o conformance_files/C032.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C003.heic -o conformance_files/C003.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C024.heic -o conformance_files/C024.jpg
Exif Data ID (cdsc) not found!
build/tifig -i conformance_files/multilayer005.heic -o conformance_files/multilayer005.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C005.heic -o conformance_files/C005.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C027.heic -o conformance_files/C027.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/multilayer004.heic -o conformance_files/multilayer004.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C021.heic -o conformance_files/C021.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C008.heic -o conformance_files/C008.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C025.heic -o conformance_files/C025.jpg
Exif Data ID (cdsc) not found!
build/tifig -i conformance_files/C038.heic -o conformance_files/C038.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C028.heic -o conformance_files/C028.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C013.heic -o conformance_files/C013.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C029.heic -o conformance_files/C029.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/multilayer003.heic -o conformance_files/multilayer003.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C036.heic -o conformance_files/C036.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C037.heic -o conformance_files/C037.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C040.heic -o conformance_files/C040.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C042.heic -o conformance_files/C042.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C022.heic -o conformance_files/C022.jpg
Exif Data ID (cdsc) not found!
build/tifig -i conformance_files/C001.heic -o conformance_files/C001.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C039.heic -o conformance_files/C039.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C041.heic -o conformance_files/C041.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C012.heic -o conformance_files/C012.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C007.heic -o conformance_files/C007.jpg
Exif Data ID (cdsc) not found!
build/tifig -i conformance_files/C018.heic -o conformance_files/C018.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C030.heic -o conformance_files/C030.jpg
Could not read HEIF image: Invalid context ID parameter.
build/tifig -i conformance_files/C006.heic -o conformance_files/C006.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C010.heic -o conformance_files/C010.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C014.heic -o conformance_files/C014.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/multilayer002.heic -o conformance_files/multilayer002.jpg
Exif Data ID (cdsc) not found!
build/tifig -i conformance_files/C034.heic -o conformance_files/C034.jpg
Could not read HEIF image: No compatible brands in file
build/tifig -i conformance_files/C016.heic -o conformance_files/C016.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/multilayer001.heic -o conformance_files/multilayer001.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new
build/tifig -i conformance_files/C015.heic -o conformance_files/C015.jpg
Grid configuration not found! tifig currently only supports .heic images created on iOS 11 devices.
If you are certain this image was created on iOS 11, please open an issue here:

https://github.com/monostream/tifig/issues/new

Do you have plan to support files from https://github.com/nokiatech/heif_conformance/tree/master/conformance_files?

snowuyl

**Comment by Flask** [comment]
Hey @snowuyl 

As already mentioned in the readme, this library is optimised for photos taken with an iOS device.

There is quite a big difference in the handling of apple heic (generic grid) and the reference heics from nokia (no grid at all). 

Cheers

**Comment by snowuyl** [comment]
Thanks for your response.
