### ISSUE TITLE
Unknown image extension: HEIC

### ISSUE THREAD

**Issue by Nobodygh** [monostream/tifig#40]
Hi

I ran the script in my folder and got the following error:
Unknown image extension: HEIC

`arie@GoldenSavage:~/Desktop/Fotos/heic/Rebekka$ ll`
`total 50160`
`drwxrwxr-x 2 arie arie    4096 Jun 15 16:21 ./`
`drwxrwxr-x 3 arie arie    4096 Jun 15 16:20 ../`
`-rw-rw-r-- 1 arie arie 1547122 May  6 04:18 IMG_1194.HEIC`
`-rw-rw-r-- 1 arie arie 1151315 May  6 04:16 IMG_1195.HEIC`
`-rw-rw-r-- 1 arie arie 1773082 May  6 04:18 IMG_1196.HEIC`
`-rw-rw-r-- 1 arie arie 1256422 May  6 04:17 IMG_1198.HEIC`
`-rw-rw-r-- 1 arie arie 1370109 May  6 04:17 IMG_1199.HEIC`
`-rw-rw-r-- 1 arie arie 1418008 May  6 04:17 IMG_1200.HEIC`
`-rw-rw-r-- 1 arie arie 1335548 May  6 04:17 IMG_1205.HEIC`
`-rw-rw-r-- 1 arie arie  971385 May  6 04:16 IMG_1206.HEIC`
`-rw-rw-r-- 1 arie arie 1068914 May  6 04:16 IMG_1207.HEIC`
`-rw-rw-r-- 1 arie arie 1050094 May  6 04:16 IMG_1208.HEIC`
`-rw-rw-r-- 1 arie arie 1187759 May  6 04:17 IMG_1209.HEIC`
`-rw-rw-r-- 1 arie arie 1458044 May  6 04:17 IMG_1210.HEIC`
`-rw-rw-r-- 1 arie arie 1726010 May  6 04:18 IMG_1211.HEIC`
`-rw-rw-r-- 1 arie arie 1855143 May  6 04:18 IMG_1212.HEIC`
`-rw-rw-r-- 1 arie arie 1386354 May  6 04:17 IMG_1214.HEIC`
`-rw-rw-r-- 1 arie arie 1254815 May  6 04:17 IMG_1216.HEIC`
`-rw-rw-r-- 1 arie arie 1156828 May  6 04:16 IMG_1217.HEIC`
`-rw-rw-r-- 1 arie arie 1704071 May  6 04:18 IMG_1218.HEIC`
`-rw-rw-r-- 1 arie arie 1308802 May  6 04:17 IMG_1219.HEIC`
`-rw-rw-r-- 1 arie arie 1626304 May  6 04:18 IMG_1220.HEIC`
`-rw-rw-r-- 1 arie arie 1590175 May  6 04:18 IMG_1221.HEIC`
`-rw-rw-r-- 1 arie arie 1000708 May  6 04:16 IMG_1222.HEIC`
`-rw-rw-r-- 1 arie arie 1329382 May  6 04:17 IMG_1225.HEIC`
`-rw-rw-r-- 1 arie arie 1414910 May  6 04:17 IMG_1226.HEIC`
`-rw-rw-r-- 1 arie arie 1073486 May  6 04:16 IMG_1227.HEIC`
`-rw-rw-r-- 1 arie arie 1210023 May  6 04:17 IMG_1228.HEIC`
`-rw-rw-r-- 1 arie arie 1346041 May  6 04:17 IMG_1229.HEIC`
`-rw-rw-r-- 1 arie arie 1250884 May  6 04:16 IMG_1231.HEIC`
`-rw-rw-r-- 1 arie arie 1436782 May  6 04:48 IMG_1234.HEIC`
`-rw-rw-r-- 1 arie arie 1403447 May  6 04:48 IMG_1235.HEIC`
`-rw-rw-r-- 1 arie arie 1628385 May  6 04:48 IMG_1236.HEIC`
`-rw-rw-r-- 1 arie arie 1244669 May  6 04:48 IMG_1237.HEIC`
`-rw-rw-r-- 1 arie arie 1278101 May  6 04:48 IMG_1238.HEIC`
`-rw-rw-r-- 1 arie arie 1815457 May  6 04:48 IMG_1240.HEIC`
`-rw-rw-r-- 1 arie arie 1551286 May  6 04:48 IMG_1241.HEIC`
`-rw-rw-r-- 1 arie arie 1710882 May  6 04:54 IMG_1242.HEIC`
`-rw-rw-r-- 1 arie arie 1385728 May  6 04:54 IMG_1243.HEIC`
`arie@GoldenSavage:~/Desktop/Fotos/heic/Rebekka$ ~/Workspace/heic/tifig *`
`Unknown image extension: HEIC`

**Comment by tschoffelen** [comment]
I think your usage is incorrect. The utility accepts `-i` and `-o` parameters to indicate the input and output files.

To learn how to do a batch conversion, have a look at the script posted in #37.
