### ISSUE TITLE
Can't load photo from iPhone

### ISSUE THREAD

**Issue by victormatheus** [monostream/tifig#43]
Hi, I'm trying to use tifig to convert from HEIC to JPG but I'm getting the following error:

./tifig -i IMG_6012.HEIC -o IMG_6012.jpg 
No ftyp box found! This cannot be a HEIF image.

Do you know what could be going on?

**Comment by victormatheus** [comment]
By the way, I'm using this binary:

https://github.com/monostream/tifig/releases/download/0.2.2/tifig-static-0.2.2.tar.gz

on Ubuntu 16.04 AMD64.

**Comment by Flask** [comment]
This is probably not an iPhone image. Could you provide a sample?

**Comment by enefry** [comment]
[Uploading IMG_0994.HEIC.zip…]()

**Comment by erjiang** [comment]
@enefry Your file is a JPEG image. I'm not sure how you got the HEIC extension but it looks like you were using a third-party app (according to the metadata).

I've seen other people make this mistake (JPEG with HEIC extension). Maybe the tool should check for JPEG magic bytes and give a special message to the user if the file is actually JPEG.

**Comment by enefry** [comment]
Oh，thanks

**Comment by erjiang** [comment]
Pull Request #53 should help with this issue by warning users if their image is actually a JPEG. I think this issue could probably be closed if nobody comes forward with this error using an actual HEIF file.
